name: Last success

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # permissions: read-all

    steps:
      - uses: actions/checkout@v3

      - name: Last successful run
        id: last_success
        run: echo "LAST_SUCCESS=$(gh api -XGET repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/workflows/last-success.yaml/runs --jq '.workflow_runs[0].run_started_at' -F status=success -F per_page=1)" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo last success
        run: echo Last success
